### ISSUE TITLE
Coveralls data shows empty while Travis generates them just fine!!!

### ISSUE THREAD

**Issue by mohislm** [nickmerwin/node-coveralls#102]
Coveralls: https://coveralls.io/builds/3141307
Travis: https://travis-ci.org/gingerjs/ginger/builds/72334250
Git Repo: https://github.com/gingerjs/ginger

**Comment by vitaly-t** [comment]
Coveralls has been fully down for 3 days now. It receives no updates from GitHub at the moment.

Whatta flop!

**Comment by BigstickCarpet** [comment]
Ok, good to know this isn't just happening to me.

Coveralls is in the middle of a big, multi-day data migration right now, so [they've said to expect some downtime](http://blog.coveralls.io/2015/07/23/Downtime-From-Big-Migration/).

**Comment by vitaly-t** [comment]
According to their own status update, they are back to business as usual. Everything seems to work again.

**Comment by nickmerwin** [comment]
@bigeasy @vitaly-t that's right! We're back up and running and all jobs in the queue have been processed.

Thanks!

**Comment by BigstickCarpet** [comment]
@nickmerwin - I'm still seeing this problem.  I assumed it was due to the upgrade, but apparently not.  All of my repos are showing a 0% code coverage on Coveralls, even though the lcov info on Travis CI says otherwise.

**Comment by nickmerwin** [comment]
@BigstickCarpet could you link me to an example?

**Comment by BigstickCarpet** [comment]
Sure thing.  Here's one that was showing 100% coverage until July 23rd, and has been showing 0% since then.

Travis CI: https://travis-ci.org/BigstickCarpet/globify/builds
Coveralls: https://coveralls.io/github/BigstickCarpet/globify

**Comment by nickmerwin** [comment]
@BigstickCarpet ok that build is processed now. Could you trigger another build when you have a chance?

Thanks.

**Comment by BigstickCarpet** [comment]
@nickmerwin - That one's fixed now, but others are still showing 0%, even after kicking-off a new CI build just now.  Is there something I need to do differently on my side?

Travis CI: https://travis-ci.org/BigstickCarpet/mock-data/builds
Coveralls: https://coveralls.io/github/BigstickCarpet/mock-data

Travis CI: https://travis-ci.org/BigstickCarpet/ono/builds
Coveralls: https://coveralls.io/github/BigstickCarpet/ono

**Comment by nickmerwin** [comment]
@BigstickCarpet ok checking that "ono" repo, could you start another build?

**Comment by BigstickCarpet** [comment]
Ok, it just completed.

**Comment by nickmerwin** [comment]
Ok all builds should be processing correctly now! 

@BigstickCarpet one more test when you get a chance?

**Comment by BigstickCarpet** [comment]
Alright, they all look good now.  Thanks for all your help!

**Comment by mohislm** [comment]
Now that the builds are processing, the updated badge shows properly from coveralls.io:
https://coveralls.io/github/gingerjs/ginger-cli?branch=master
But the GitHub repo shows `unknown`, although I did couple more pushes:
https://github.com/gingerjs/ginger-cli

**Comment by nickmerwin** [comment]
@mohislm looks like your badge is showing properly now, cheers!

**Comment by a11smiles** [comment]
i'm having the same issue... my .lcov is being generated, but coveralls.io shows nothing for the build.

Here's my .lcov coming from travis:
```
TN:
SF:/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/angular2-template-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/tslint-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/src/test.ts
FN:15,(anonymous_1)
FN:23,(anonymous_2)
FN:30,(anonymous_3)
FN:32,(anonymous_4)
FNF:4
FNH:4
FNDA:1,(anonymous_1)
FNDA:1,(anonymous_2)
FNDA:1,(anonymous_3)
FNDA:1,(anonymous_4)
DA:1,1
DA:3,1
DA:4,1
DA:5,1
DA:6,1
DA:7,1
DA:8,1
DA:15,1
DA:18,1
DA:24,1
DA:30,1
DA:32,1
LF:12
LH:12
BRF:0
BRH:0
end_of_record
TN:
SF:/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/angular2-template-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/tslint-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/src/polyfills.ts
FNF:0
FNH:0
DA:3,1
DA:4,1
DA:5,1
DA:6,1
DA:7,1
DA:8,1
DA:9,1
DA:10,1
DA:11,1
DA:12,1
DA:13,1
DA:14,1
DA:15,1
DA:16,1
DA:18,1
DA:19,1
LF:16
LH:16
BRF:0
BRH:0
end_of_record
TN:
SF:/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/angular2-template-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/node_modules/tslint-loader/index.js!/home/travis/build/DiscipledChurch/Multipli-ChMS/src/app/app.component.ts
FN:8,(anonymous_3)
FNF:1
FNH:1
FNDA:4,(anonymous_3)
DA:1,1
DA:3,1
DA:8,2
DA:9,3
DA:10,1
LF:5
LH:5
BRF:0
BRH:0
end_of_record
```

https://travis-ci.org/DiscipledChurch/Multipli-ChMS/builds/174575974
https://coveralls.io/builds/8747835

**Comment by a11smiles** [comment]
here's the output for `stdout` flag:

{"source_files":[],"git":{"head":{"id":"HEAD","committer_name":"Travis CI User","committer_email":"travis@example.org","message":"adding dist","author_name":"Travis CI User","author_email":"travis@example.org"},"branch":"develop","remotes":[{"name":"heroku","url":"https://git.heroku.com/multipli-test.git"},{"name":"origin","url":"https://github.com/DiscipledChurch/Multipli-ChMS.git"}]},"run_at":"2016-11-10T02:08:15.079Z","service_name":"travis-ci","service_job_id":"174662591"}

**Comment by a11smiles** [comment]
#143

**Comment by a11smiles** [comment]
#143 created new issue

**Comment by tobslob** [comment]
Hello, I am having a similar issue, my travis built fine, no build in coveralls. I have search many resources but did not solved it. I am a newbie, and this is already tearing me apart. My app is a node.js app
