### ISSUE TITLE
Ignoring .js files

### ISSUE THREAD

**Issue by rubenafo** [nickmerwin/node-coveralls#116]
I have some automatically-generated source files which I'm not covering with the tests so I'd like to coveralls skip those. 
How can I do that using coveralls for NodeJs?

Thanks!

**Comment by leggsimon** [comment]
Yeah likewise, I'd like to actively ignore some files that aren't expected to be tested within my repo. I wonder if theres there possibility of a comment line at the top of the file (a bit like eslint's `/* eslint-disable */`) or the possibly a dotfile approach.

Will have a little look through the code at some point and see how easy a PR might be but any guidance from the project maintainer would be excellent.

**Comment by leggsimon** [comment]
:man_facepalming: I've just realised that my issue is not with `node-coveralls` I'm using [`nyc`](https://github.com/istanbuljs/nyc) and the fix therein lies. Apologies, this can probably be closed now.
