### ISSUE TITLE
Update dependency request version

### ISSUE THREAD

**Issue by taoyuan** [nickmerwin/node-coveralls#149]
`request@2.75.0` using `node-uuid`, but it has been deprecated. 

Please update `request` to `2.79.1` to supress the warning.

Maybe we cloud upgrade all dependencies to latest version.

**Comment by OmgImAlexis** [comment]
Any updates on this? This has been open for 5 months now. 😞

**Comment by dogboydog** [comment]
Another reason to do this: the version of request used uses a vulernable `tough-cookie` dependency

https://nodesecurity.io/advisories/525

`request` should be updated to the latest version which uses a non-vulnerable `tough-cookie`
