### ISSUE TITLE
Upgrade request dependency in package.json

### ISSUE THREAD

**Issue by arekkas** [nickmerwin/node-coveralls#153]
node-coveralls is using `request: 2.75` which yields `warning coveralls > request > node-uuid@1.4.7: use uuid module instead`. This has been fixed in request with version `>=2.79`. Please consider upgrading the dependency :)

**Comment by haysclark** [comment]
👍

**Comment by revelt** [comment]
+1

**Comment by revelt** [comment]
@arekkas please close this issue because there's one already - #149
