### ISSUE TITLE
Readme badge "coverage unknown"

### ISSUE THREAD

**Issue by samit4me** [nickmerwin/node-coveralls#156]
This is more of a question than an issue, so I hope that is okay?

The Readme badge for [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/) is no longer working:
![coveralls_unknown](https://cloud.githubusercontent.com/assets/3248531/22485288/cfbb3096-e850-11e6-9d7c-eae77767d8a5.png) - https://coveralls.io/repos/github/react-boilerplate/react-boilerplate/badge.svg

On Travis CI it is building correctly:
![passing](https://cloud.githubusercontent.com/assets/3248531/22485352/2276da88-e851-11e6-9c4e-7e7f240589e3.png) - https://travis-ci.org/react-boilerplate/react-boilerplate.svg

### Info
- Just recently (about a week ago) the repo was moved from `/mxstbr/react-boilerplate` to an organisation `/react-boilerplate/react-boilerplate`.
- In Travis CI setting, there is an Environment Variables set `COVERALLS_REPO_TOKEN`
- [Our open issue](https://github.com/react-boilerplate/react-boilerplate/issues/1535)

### Things we have tried
- We removed the Environment Variables based on the [docs](https://www.npmjs.com/package/coveralls#usage) and made sure a build was done.
- Tried to purge any cache on github using the command `curl -X PURGE https://camo.githubusercontent.com/...` based on this [comment](https://github.com/lemurheavy/coveralls-public/issues/116#issuecomment-242875974).

Does anyone have any ideas on what we can try next. The only option I see an have not tried is regenerate the repo token, would that help?

**Comment by samit4me** [comment]
UPDATE:
- I have regenerated the token.
- Removed all environment variables on Travis CI.
- Performed a build on Travis CI (no build history on coveralls 😞)
- On Travis CI I then added 2 environment variables COVERALLS_SERVICE_NAME and COVERALLS_REPO_TOKEN with the appropriate values.
- Performed a build on Travis CI (no build history on coveralls 😞)
- Then I added the same 2 environment variables on my local machine and piped the lcov output to `./node_modules/coveralls/bin/coveralls.js` (now we have a build showing on coveralls, but the badge still "coverage unknown"

So it seems there are two issues,

1. Travis CI is not communicating with coveralls.
1. Coveralls is not showing the correct badge.

Any help on this would be greatly appreciated.

**Comment by nickmerwin** [comment]
Hi @samit4me the 2 builds on Coveralls are for the dev branch; the badge you have on the README is for master -- if you'd rather display the dev branch badge the code would be:

```markdown
[![Coverage Status](https://coveralls.io/repos/github/react-boilerplate/react-boilerplate/badge.svg?branch=dev)](https://coveralls.io/github/react-boilerplate/react-boilerplate?branch=dev)
```

[![Coverage Status](https://coveralls.io/repos/github/react-boilerplate/react-boilerplate/badge.svg?branch=dev)](https://coveralls.io/github/react-boilerplate/react-boilerplate?branch=dev)

**Comment by samit4me** [comment]
Hi @nickmerwin, thank you for the response :)

I have tried triggering both master build and dev builds on Travis CI but Coveralls was not getting updated. The badge you are referring to was built by running coverage locally on my PC using the environment variables COVERALLS_SERVICE_NAME and COVERALLS_REPO_TOKEN.

After trial and error, it seems the problem is that Travis CI is not updating Coveralls. According to the docs Travis CI should not need environment variables, so I have tried with and without them, but no luck :disappointed: The only time coveralls gets updated is when I run it from my local machine.

Not sure what else to try, do you have any suggestions?

**Comment by nickmerwin** [comment]
@samit4me ah ok I see in the job output that the lcov file is missing:
https://travis-ci.org/react-boilerplate/react-boilerplate/jobs/198492912#L540

Perhaps the `npm run build` script is removing the lcov.info before the `after_success` runs on Travis.

**Comment by samit4me** [comment]
Oh wow how embarrassing haha, I never realized ` $ npm run coveralls` could be expanded to give useful info. Thank you so much, will look into why it's missing cheers

**Comment by nickmerwin** [comment]
Sounds good, closing the issue for now. Happy covering!
