### ISSUE TITLE
No Data transferred

### ISSUE THREAD

**Issue by aeimer** [nickmerwin/node-coveralls#165]
Hi,
we want to send to send the lcov-file from our travis build to coverall.io. The builds are registered by coveralls.io, but there are no coverage data.
What are we doing wrong?

Our repo/branch is here: https://github.com/khase/geli/tree/feature/00-coveralls
- Coveralls: https://coveralls.io/github/khase/geli
- Travis: https://travis-ci.org/khase/geli/branches

In the travis-file we add the dependcies: `npm install sshpk coveralls`. We then test our code and the test create a lcov.info-file looking like this:
```
TN:
SF:/home/travis/build/khase/geli/api/build/src/server.ts
FN:20,(anonymous_1)
FN:25,(anonymous_2)
FNF:2
FNH:0
FNDA:0,(anonymous_1)
FNDA:0,(anonymous_2)
DA:1,0
DA:2,0
DA:3,0
DA:4,0
DA:5,0
DA:6,0
DA:8,0
DA:9,0
DA:10,0
DA:16,0
DA:21,0
DA:22,0
DA:27,0
DA:29,0
DA:31,0
DA:37,0
DA:39,0
DA:40,0
DA:42,0
DA:43,0
DA:49,0
LF:21
LH:0
BRF:0
BRH:0
end_of_record
TN:
SF:/home/travis/build/khase/geli/api/build/src/test.ts
FN:2,addTwo
FNF:1
FNH:0
FNDA:0,addTwo
DA:2,1
DA:3,0
DA:4,0
LF:3
LH:1
BRF:0
BRH:0
end_of_record
```

After the test we call: `cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -v`. This prints us only this warning:`Repo token could not be determined.  Continuing without it.This is necessary for private repos only, so may not be an issue at all.`

How can we push the lcov to coveralls?

coveralls-version: 2.13.0

**Comment by Bamieh** [comment]
same issue here.
```
cat ./coverage/lcov.info | coveralls -v 
[warn] "2017-05-09T11:48:23.541Z"  'Repo token could not be determined.  Continuing without it.This is necessary for private repos only, so may not be an issue at all.'
```

coveralls-version: ^2.13.1

**Comment by aeimer** [comment]
Hey @nickmerwin, is this a problem by the package 'node-coveralls' or anywhere else like the lcov-file or coveralls.io-API?

Thank you very much :)

**Comment by khase** [comment]
finally fixed this issue
lemurheavy/coveralls-public#1024

**Comment by aeimer** [comment]
Will close, see h-da/geli for the solution
