### ISSUE TITLE
Inaccurate Coveralls reported

### ISSUE THREAD

**Issue by priley86** [nickmerwin/node-coveralls#194]
Hi,

I'm looking for a simple way to trace the code coverage reported in my repo here:
https://coveralls.io/github/patternfly/patternfly-react?branch=master

It does not appear to be reporting correctly as `yarn test` reports the following:
```
========================Coverage summary 
Statements   : 82.05% ( 1902/2318 )
Branches     : 61.15% ( 639/1045 )
Functions    : 72.76% ( 406/558 )
Lines        : 82.57% ( 1866/2260 )
==============================================
```
I would expect to see something more along these lines for the aggregate percentage on the repo badge. I'm not sure how the percentage in my badge is calculated - could someone explain this?

The raw lcov.info generated can be found here:
https://pastebin.com/raw/588FggQg

Can you kindly point me in the right direction? We recently upgraded to a monorepo structure, but I don't think this is the cause of the issue. I am using the latest release of node-coveralls it seems.

**Comment by brendanlucas** [comment]
Late to the party but I hope this helps...

I saw a similar problem and tracked it down to Coveralls configuration. There is a setting for `Branch Coverage` at the repo level. Disable this and you will find that the website will show the same value as the cli shows.

Now that I am aware of this, I am leaving the Branch Coverage setting enabled as I feel it is more accurate.

**Comment by priley86** [comment]
Thanks it might help someone - we had already migrated to codecov unfortunately ;( ... closing this.
