### ISSUE TITLE
incorrect coverage reporting on readme badge

### ISSUE THREAD

**Issue by gsingh04** [nickmerwin/node-coveralls#212]
[Here](https://github.com/gsingh04/aws-limit-monitor/blob/master/.travis.yml) is my .travis.yml

I have multiple package.json in my project and trying to combine multiple coverage reports to show up on my [readme](https://github.com/gsingh04/aws-limit-monitor/blob/master/README.md). However, with `COVERALLS_PARALLEL=true` I don't see it getting updated. The coverage shows up correctly on coveralls.io builds but not on the readme badge.

**Comment by nickmerwin** [comment]
Hi @gsingh04 I'm seeing the correct 46% badge on your repo's readme currently. Github sometimes sets aggressive caches headers on these images so there are times when your browser may have an old copy. If you're still seeing an outdated badge could you check in a different browser?

**Comment by gsingh04** [comment]
thanks
