### ISSUE TITLE
Jest instructions cause CI to pass on failed tests

### ISSUE THREAD

**Issue by mlms13** [nickmerwin/node-coveralls#230]
The README provides these instructions for Jest integration:

```sh
jest --coverage --coverageReporters=text-lcov | coveralls
```

But in this case, if a test doesn't pass, Jest's non-zero exit status is swallowed by `| coveralls` and turned into a `0`, which tricks Circle (and probably most other CIs?) into thinking the build was a success.

The command suggested in [this comment](https://github.com/nickmerwin/node-coveralls/issues/126#issuecomment-332081774) shouldn't have the same issue:

```sh
jest --coverage && cat ./coverage/lcov.info | coveralls
```

**Comment by AndreMiras** [comment]
Yes I confirm I get the issue with Travis too. Another way to make the pipe file would be to `set -o pipefail`.
