### ISSUE TITLE
Couldn't Find Repository in GitHub Actions

### ISSUE THREAD

**Issue by stevenvachon** [nickmerwin/node-coveralls#232]
I just switched from Travis CI to GitHub Actions (beta) and it's failing. Nothing else in the repo was changed.

This seems very similar to #231.

I tried adding `COVERALLS_REPO_TOKEN` env var, per #166, which fixed it. Should this be necessary, though?

**Comment by nickmerwin** [comment]
Hi @stevenvachon can you link me to your repo? Or, if it's private, paste your workflow.yml file here.

**Comment by stevenvachon** [comment]
https://github.com/stevenvachon/broken-link-checker/blob/master/.github/workflows/tests.yml

**Comment by XhmikosR** [comment]
Personally I notice the branch name doesn't show up after switching to GitHub Actions. I do have `COVERALLS_REPO_TOKEN`

https://coveralls.io/github/validator/grunt-html

**Comment by nickmerwin** [comment]
Hi @XhmikosRand @stevenvachon it would be best to switch to the official Action: 

https://github.com/marketplace/actions/coveralls-github-action

Otherwise, you can fix the missing branch by explicitly setting this env var in the step:

`COVERALLS_GIT_BRANCH: $GITHUB_REF`

**Comment by XhmikosR** [comment]
To clarify, the correct is this:

```yml
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
```

But this results in `refs/head/branch`, not just branch.

As for the GitHub Action, I wasn't even aware there was one. I would switch to it, but I don't like the extra comments, which from the docs, I can't see any way to disable them.

**Comment by stevenvachon** [comment]
Do we no longer need to `npm install coveralls`?
