### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by XhmikosR** [nickmerwin/node-coveralls#260]
@nickmerwin can you push the "recent" 3.0.5, 3.0.6 and 3.0.7 tags to the repo?

BTW for the future you should automate your workflow by using [`npm version`](https://docs.npmjs.com/cli/version) and then do `git push --tags && npm publish`.

You could probably automate this if needed, but it's not super important as long as you do the above.

**Comment by XhmikosR** [comment]
@nickmerwin if you switched to `np` or something else, feel free to close this issue. Although, it'd be nice to have the missing tags too, but if you can't add them now, we'll live without them 😇

**Comment by nickmerwin** [comment]
@XhmikosR done! And yes I'll be using `np` from now on. 

Thank you for the nudge.
