### ISSUE TITLE
Update sinon

### ISSUE THREAD

**Issue by cktang88** [nickmerwin/node-coveralls#261]
Currently uses sinon-restore, which hasn't been updated in 6 years, and depends on sinon 1.5.2. Sinon is currently on 7.5.0 which brings a lot of improvements/features

**Comment by XhmikosR** [comment]
Feel free to submit a PR :)

**Comment by guimard** [comment]
PR submitted ;-)

**Comment by guimard** [comment]
And fixed (test passed)
