### ISSUE TITLE
Failure on git commits that lack email

### ISSUE THREAD

**Issue by nordstrand** [nickmerwin/node-coveralls#86]
``` javascript
TypeError: Cannot read property 'slice' of null
    at node_modules/coveralls/lib/fetchGitData.js:69:53
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
```

**Comment by addaleax** [comment]
@nickmerwin I guess you can close this one now :)

**Comment by nickmerwin** [comment]
@addaleax thanks for the heads up!

**Comment by cdaringe** [comment]
hello:

i still have this issue.  are we confident that it is resolved?  i will provide some context to demonstrate my repeated issue:

- im on `"coveralls": "^2.11.9"`, per [here](https://github.com/cdaringe/pouchy/blob/master/package.json#L36)
- my CI fails on the latest build, per [here](https://codeship.com/projects/103658/builds/14625748)
- failing command: `cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js`

the failure output is:

```js
/home/rof/src/github.com/cdaringe/pouchy/node_modules/coveralls/lib/fetchGitData.js:69
var items = response.match(REGEX_COMMIT_DETAILS).slice(1);
^

TypeError: Cannot read property 'slice' of null
at /home/rof/src/github.com/cdaringe/pouchy/node_modules/coveralls/lib/fetchGitData.js:69:53
at ChildProcess.exithandler (child_process.js:204:7)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

thanks!

**Comment by addaleax** [comment]
Hi, could you point to the commit which has this problem? I don’t see any ones that have no committer email and can’t access the codeship page you linked to.

**Comment by cdaringe** [comment]
hello:

~~the latest commit in my linked package suffers the issue.  it was working last week, with no change to the dependencies.  i'm sorry that the codeship link isn't public. :$~~

~~as proof of claim (not that there's trust issues or anything :) ), here's a snapshot showing the github commit:~~

~~<img width="866" alt="screen shot 2016-05-11 at 12 47 45 am" src="https://cloud.githubusercontent.com/assets/1003261/15172294/53363080-1712-11e6-9b41-64f97dea523d.png">~~

the commit listed in the above screenshot apparently _doesn't exist in my repo_?  i didn't meddle with history.  how peculiar.  well, my repo's `master` HEAD checks out, and coverage seems to be working there.  i will revisit this if i stumble upon any further clues as to the chain of events producing a mysterious commit and hence the broken coveralls script.

thanks for your response!

**Comment by addaleax** [comment]
`git reflog` may help you if you did do something locally, but yeah, sounds like there’s some other weird thing going on…
